language: node_js
node_js:
  - "4"
  - "0.10"

script:
  - "npm run nsp && npm run lint && npm test"

notifications:
  email: false

sudo: false

before_install:
  - "npm install -g npm@latest"

# so that travis doesn't complain about a missing npm
before_script:
  - npm link npm
